### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by happsky** [databricks/spark-deep-learning#133]
>>> featurizer = DeepImageFeaturizer(inputCol="image", outputCol="features", modelName="ResNet50")
>>> lr = LogisticRegression(maxIter=20, regParam=0.05, elasticNetParam=0.3, labelCol="label")
>>> p = Pipeline(stages=[featurizer, lr])
>>> p_model = p.fit(train_df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ho/image_classification_spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/base.py", line 64, in fit
    return self._fit(dataset)
  File "/home/ho/image_classification_spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/pipeline.py", line 106, in _fit
    dataset = stage.transform(dataset)
  File "/home/ho/image_classification_spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/base.py", line 105, in transform
    return self._transform(dataset)
  File "/tmp/spark-86622d41-f3cf-42ef-ac05-9fb03bf474d1/userFiles-39aeced1-93ed-43f8-be88-30299b05e4a4/databricks_spark-deep-learning-0.1.0-spark2.1-s_2.11.jar/sparkdl/transformers/named_image.py", line 159, in _transform
  File "/home/ho/image_classification_spark/spark-2.1.1-bin-hadoop2.7/python/pyspark/ml/base.py", line 105, in transform
    return self._transform(dataset)
  File "/tmp/spark-86622d41-f3cf-42ef-ac05-9fb03bf474d1/userFiles-39aeced1-93ed-43f8-be88-30299b05e4a4/databricks_spark-deep-learning-0.1.0-spark2.1-s_2.11.jar/sparkdl/transformers/named_image.py", line 212, in _transform
  File "/tmp/spark-86622d41-f3cf-42ef-ac05-9fb03bf474d1/userFiles-39aeced1-93ed-43f8-be88-30299b05e4a4/databricks_spark-deep-learning-0.1.0-spark2.1-s_2.11.jar/sparkdl/transformers/named_image.py", line 230, in _buildTFGraphForName
TypeError: not enough arguments for format string

**Comment by lukewgreen** [comment]
I'm getting the same error when trying to load ResNet50
