### ISSUE TITLE
Save a pyspark ml pipeline model

### ISSUE THREAD

**Issue by Liangmp** [databricks/spark-deep-learning#191]
Hi,

I am trying to save a model for future use, belowed are the code:
```
p_model = p.fit(train_df)
p_model.save("hdfs:///ml_model")
```
However,  I get the following errer:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/spark-2.4.0-bin-hadoop2.7/python/pyspark/ml/util.py", line 244, in save
    self.write().save(path)
  File "/opt/spark-2.4.0-bin-hadoop2.7/python/pyspark/ml/util.py", line 136, in save
    self.saveImpl(path)
  File "/opt/spark-2.4.0-bin-hadoop2.7/python/pyspark/ml/pipeline.py", line 225, in saveImpl
    PipelineSharedReadWrite.validateStages(stages)
  File "/opt/spark-2.4.0-bin-hadoop2.7/python/pyspark/ml/pipeline.py", line 348, in validateStages
    stage.uid, type(stage))
ValueError: ('Pipeline write will fail on this pipeline because stage %s of type %s is not MLWritable', 'DeepImageFeaturizer_bbeb5c2d479e', <class 'sparkdl.transformers.named_image.DeepImageFeaturizer'>)
```
I find a similar issue [here](https://github.com/databricks/spark-deep-learning/issues/142) but we have a different error. Can any one give me some help?

**Comment by Liangmp** [comment]
It seems that stages[1] LogisticRegressionModel can be saved, while stages[0] DeepImageFeaturizer can not be saved. Pipeline model p_model contains both of these two stages, therefore, it can not be saved.
```
>>> print(type(p_model.stages[0]))
<class 'sparkdl.transformers.named_image.DeepImageFeaturizer'>
>>> print(type(p_model.stages[1]))
<class 'pyspark.ml.classification.LogisticRegressionModel'>
```
