### ISSUE TITLE
AttributeError: 'PipelinedRDD' object has no attribute 'toDF'

### ISSUE THREAD

**Issue by allwefantasy** [databricks/spark-deep-learning#48]
Code: 

```
from pyspark import *
from sparkdl import readImages
image_df = readImages("/data/myimages")
```

When run this code，Exceptioin Raised:

```
/Users/allwefantasy/python2.7/tensorflow/bin/python /Users/allwefantasy/CSDNWorkSpace/spark-deep-learning/python/tests/Test.py
Using TensorFlow backend.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
17/09/18 10:08:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "/Users/allwefantasy/CSDNWorkSpace/spark-deep-learning/python/tests/Test.py", line 3, in <module>
    image_df = readImages("/data/myimages")
  File "/Users/allwefantasy/CSDNWorkSpace/spark-deep-learning/python/sparkdl/image/imageIO.py", line 231, in readImages
    return _readImages(imageDirectory, numPartition, SparkContext.getOrCreate())
  File "/Users/allwefantasy/CSDNWorkSpace/spark-deep-learning/python/sparkdl/image/imageIO.py", line 236, in _readImages
    imageData = filesToDF(sc, imageDirectory, numPartitions=numPartition)
  File "/Users/allwefantasy/CSDNWorkSpace/spark-deep-learning/python/sparkdl/image/imageIO.py", line 219, in filesToDF
    return rdd.toDF(schema)
```

**Comment by phi-dbq** [comment]
Hi @allwefantasy, would you please indicate the version of Spark you are using? 
This [StackOverflow thread](https://stackoverflow.com/questions/32788387/pipelinedrdd-object-has-no-attribute-todf-in-pyspark) might be useful.
Thanks!

**Comment by allwefantasy** [comment]
spark 2.2.0 .  Yes, i have aready fix this by adding `spark = SparkSession(sc) `  in imageIO.py's filesToDF。 Maybe we should fix this ?
