### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by exitNA** [databricks/spark-deep-learning#91]
hi, I am trying to use python 3 to import sparkdl, i found this error, anyone who can help me?
```
Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparkdl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mark/tool/python3/lib/python3.6/site-packages/sparkdl/__init__.py", line 15, in <module>
    from .graph.input import TFInputGraph
  File "/home/mark/tool/python3/lib/python3.6/site-packages/sparkdl/graph/input.py", line 17, in <module>
    import tensorflow as tf
  File "/home/mark/tool/python3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/mark/tool/python3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 30, in <module>
    import traceback
  File "/home/mark/tool/python3/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/mark/tool/python3/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/home/mark/tool/python3/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/home/mark/tool/python3/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
>>> 
```

**Comment by phi-dbq** [comment]
Hi @exitNA, this is likely caused by python not finding the right `enum` package.
Hope that this helps. 
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by exitNA** [comment]
thanks @phi-dbq i have fixed this problem

**Comment by testevez** [comment]
What was the fix?

**Comment by JasonDitto** [comment]
@exitNA what was the fix?
